<a href="https://colab.research.google.com/github/mkshowhardo/Google-colab/blob/main/categorcical_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import pandas as pd
import numpy as np

In [56]:
df = pd.read_csv('customer.csv')

In [57]:
df.head(5)

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [58]:
df = df.iloc[:,2:]

In [59]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [60]:
from sklearn.model_selection import  train_test_split

x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1], test_size= 0.3)

In [61]:
x_train

review education
40     Good    School
47     Good        PG
12     Poor    School
6      Good    School
24  Average        PG
7      Poor    School
41     Good        PG
19     Poor        PG
45     Poor        PG
25     Good    School
17     Poor        UG
13  Average    School
35     Poor    School
29  Average        UG
39     Poor        PG
14     Poor        PG
38     Good    School
27     Poor        PG
37  Average        PG
0   Average    School
23     Good    School
20  Average    School
43     Poor        PG
31     Poor    School
48     Good        UG
4   Average        UG
10     Good        UG
44  Average        UG
8   Average        UG
26     Poor        PG
34  Average    School
1      Poor        UG
16     Poor        UG
32  Average        UG
3      Good        PG

In [62]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [63]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [64]:
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

In [65]:
x_train

array([[2., 0.],
       [2., 2.],
       [0., 0.],
       [2., 0.],
       [1., 2.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [1., 2.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [1., 1.],
       [1., 1.],
       [0., 2.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [2., 2.]])

In [67]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [68]:
from sklearn.preprocessing import LabelEncoder

In [69]:
le = LabelEncoder()

In [74]:
le.fit(y_train)

LabelEncoder()

In [75]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [76]:
le.classes_

array([0, 1])

In [77]:
y_train

array([0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0])